package com.example.stackexchangequestion.utilities

const val TAG_TAGS              = "tags"
const val TAG_OWNER             = "owner"
const val TAG_USER_ID           = "user_id"
const val TAG_USER_TYPE         = "user_type"
const val TAG_ACCECPT_RATE      = "accept_rate"
const val  TAG_PROFILE_IMAGE    = "profile_image"
const val TAG_DISPLAY_NAME      = "display_name"
const val TAG_LINK              = "link"
const val TAG_IS_ANSWERED       = "is_answered"
const val TAG_VIEW_COUNT        = "view_count"
const val TAG_ANSWER_COUNT      = "answer_count"
const val TAG_SCORE             = "score"
const val TAG_LAST_ACTIVITY_DATE= "last_activity_date"
const val TAG_CREATION_DATE     = "createion_date"
const val TAG_QUESTION_ID       = "question_id"
const val TAG_CONTENT_LICENSE   = "content_license"
const val TAG_TITLE             = "title"
const val TAG_REPUTATION        = "reputation"